### ISSUE TITLE
CMakeLists.txt not found (Directory incorrect)

### ISSUE THREAD

**Issue by JamesYangLim** [lukka/CppBuildTasks#1]
In azure-pipelines.yml I have a run-cmake task script as shown below:

```
- task: run-cmake@0
  inputs:
    cmakeListsOrSettingsJson: CMakeListsTxtAdvanced
    cmakeListsTxtPath: '$(Build.SourcesDirectory)/CMakeLists.txt'
    useVcpkgToolchainFile: true
    buildDirectory: '$(Build.ArtifactStagingDirectory)'
    ninjaPath: '$(Build.BinariesDirectory)/downloads/'
    cmakeAppendedArgs: '-G Ninja -DCMAKE_BUILD_TYPE=Release'
```

When I do a build, I am getting error saying CMakeLists.txt not found in "D:/a/1/a" which seems to be a wrong directory. I specified the cmakeListsTxtPath to $(Build.SourcesDirectory)/CMakeLists.txt as shown in the yml script above.

```
##[section]Starting: runcmake
==============================================================================
Task         : Run CMake
Description  : Run CMake (and optionally vcpkg and Ninja) with a CMakeLists.txt or with CMakeSettings.json created with Visual Studio
Version      : 0.3.11
Author       : Luca Cappa
Help         : [More information](https://github.com/lukka/CppBuildTasks/blob/master/README.md)
==============================================================================
[command]"C:\Program Files\CMake\bin\cmake.exe" -G Ninja -DCMAKE_BUILD_TYPE=Release "-DCMAKE_MAKE_PROGRAM=d:\a\1\b\downloads\" d:\a\1\s"
CMake Warning:
  No source or binary directory provided.  Both will be assumed to be the
  same as the current working directory, but note that this warning will
  become a fatal error in future CMake releases.


CMake Error: The source directory "D:/a/1/a" does not appear to contain CMakeLists.txt.
Specify --help for usage, or press the help button on the CMake GUI.
##[error]Error: CMake failed with error: '1'.
##[error]CMake failed with error: 'Error: CMake failed with error: '1'.'.
##[section]Finishing: runcmake
```

I do not understand why it is looking into a wrong directory although I have already specified a directory. Any idea?
