### ISSUE TITLE
Caching fails when not using vcpkg as a submodule

### ISSUE THREAD

**Issue by drbenmorgan** [lukka/CppBuildTasks#23]
I've been trying out CppBuildTasks for some cross-platform builds (and thanks for a great resource for this!), and have run into a small issue with caching the results of `run-vcpkg` when `vcpkg` is *not* a submodule. I realise that's not the recommended use case, but thought I'd report what I found just in case this is a real bug or requires additional documentation/warning on the non-submodule case.

What seems to happen is that in the non-submodule case, the `run-vcpkg` task expects a file named `vcpkg_remote_url.last` to exist in the `vcpkg` root. The task creates this file fine, but it is *not* listed as an exception in the generated `.artifactsignore` file created for a connected `Cache@2` task. Whilst the cache tasks restores `vcpkg.exe`, `.git` and `installed` o.k., the lack of the `vcpkg_remore_url.last` file causes the `run-vcpkg` task to remove the vcpkg directory and start from scratch (so rebuilding `vcpkg.exe` and all wanted packages).

I was able to get things working for this case but setting the hidden `vcpkgArtifactIgnoreEntries` variable to the form before #15 was merged:

```yaml
- task: run-vcpkg@0 
    displayName: 'Run vcpkg'
    inputs:
      vcpkgGitCommitId: $(vcpkgGitRef)
      vcpkgTriplet: x64-windows
      vcpkgArguments: fmt libgit2 gtest
      vcpkgArtifactIgnoreEntries: "buildtrees\ndownloads\npackages\n"
```

That's crude, but gets a cache that's restored and reused o.k.

This was only an experiment for a small library project, hence not using `vcpkg` as a submodule. I can go in that direction if that's going to be the only method supported by CppBuildTasks going forward.
